networks:
  my-isolated-network:
    name: my-isolated-network-name

services:
  multicast-emitter-archer1:
    image: pw3:latest
    command:
      - enemy
      - --pause=10000
      - --damage=15000
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
      - --name=archer1

  multicast-emitter-archer2:
    image: pw3:latest
    command:
      - enemy
      - --pause=3000
      - --damage=1000
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
      - --name=archer2
  server:
    image: pw3:latest
    command:
      - server
      - --hostm=239.1.1.1
      - --hostu=localhost
      - --portm=9876
      - --portu=1234
      - --interface=eth0
    ports:
      - "1234:1234"