networks:
  my-isolated-network:
    name: my-isolated-network-name

services:
  warrior:
    image: ghcr.io/betterblood/tower-defense:latest
    command:
      - enemy
      - --pause=10000
      - --damage=500
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
      - --name=archer1

  archer:
    image: ghcr.io/betterblood/tower-defense:latest
    command:
      - enemy
      - --pause=3000
      - --damage=250
      - --host=239.1.1.1
      - --port=9876
      - --interface=eth0
      - --name=archer2
  tower:
    image: ghcr.io/betterblood/tower-defense:latest
    command:
      - server
      - --hostm=239.1.1.1
      - --portm=9876
      - --portu=1234
      - --baseHP=10000
      - --baseProtection=0
      - --interface=eth0
  ally:
    image: ghcr.io/betterblood/tower-defense:latest
    command:
      - client
      - --host=tower