@startuml
'https://plantuml.com/sequence-diagram

emitter -> server: ATTACK archer 10
emitter -> server: ATTACK archer 10

@enduml


@startuml
'https://plantuml.com/sequence-diagram

client -> server: PROTECT HEAL 10
client -> server: PROTECT DEFEND 10
server -> client: ERROR_CD <time_left>

client -> server: GET_INFO
server -> client: ANSWER <info>

server -> client: GAME_LOST

@enduml